#! env python3

import secrets, string, argparse

def mksecret(length):
    alphabet = string.ascii_letters + string.digits + "!%$@^*{}()[]"
    return ''.join(secrets.choice(alphabet) for i in range(length))

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate a random secret')
    parser.add_argument('length', 
                        type=int, 
                        help='Length of the secret', 
                        default=24, nargs='?')
    args = parser.parse_args()
    print(mksecret(args.length))